# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate new localized screenshots"

  # my lanes
  lane :screenshots do
    #fastlane deliver download_metadata
      capture_screenshots(workspace: "dckx.xcworkspace", scheme: "dckxUITests")
      frameit(rose_gold: true)
    deliver
  end
  
end
